app/main/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, \
    session, flash, jsonify
from datetime import datetime as dt
from sqlalchemy import func
from flask_login import current_user, login_required
from app.aiapi import generateChatResponse
from app.extensions import db
from app.models import GameQuestions, GameAnswers, Quiz, Scores

main = Blueprint('main', __name__)


@main.route('/dashboard')
@login_required
def dashboard():
    user_id = current_user.id

    user_quizzes = Quiz.query.filter_by(user_id=user_id).order_by(Quiz.datetime.desc()).all()
    public_quizzes = Quiz.query.filter(Quiz.public_quiz, Quiz.user_id != user_id).order_by(Quiz.datetime.desc()).all()

    for quiz in user_quizzes:
        quiz.datetime = quiz.datetime.strftime('%B %d, %Y %H:%M')  # Format the date as desired

    for quiz in public_quizzes:
        quiz.datetime = quiz.datetime.strftime('%B %d, %Y %H:%M')  # Format the date as desired

    return render_template('main/dashboard.html', user_quizzes=user_quizzes, public_quizzes=public_quizzes)


@main.route('/<int:user_id>/quiz/<int:quiz_id>', methods=['GET'])
@login_required
def quiz_page(user_id, quiz_id):
    print(user_id, quiz_id)
    quiz = Quiz.query.filter_by(user_id=user_id, id=quiz_id).first()
    print(quiz)
    if quiz is None:
        flash('Quiz not found', 'error')
        return redirect(url_for('main.dashboard'))

    questions = GameQuestions.query.filter_by(quiz_id=quiz.id).all()
    if not questions:
        flash('No questions found for the quiz', 'error')
        return redirect(url_for('main.dashboard'))

    answer_options = []
    for question in questions:
        options = GameAnswers.query.filter_by(question_id=question.id).all()
        answer_options.extend(options)

    return render_template('main/generated-quiz.html', quiz=quiz, questions=questions, answer_options=answer_options)


@main.route('/submit-quiz', methods=['POST'])
@login_required
def submit_quiz():
    try:
        user_answers = {}
        for key, value in request.form.items():
            if key.startswith('answer_'):
                question_id = int(key.split('_')[1])
                user_answers[question_id] = value

        # Fetch correct answers from the database based on the question IDs
        correct_answers = {}
        for question_id in user_answers.keys():
            question = GameQuestions.query.get(question_id)
            if question is not None:
                correct_answer = GameAnswers.query.filter_by(question_id=question.id, correct_answer=True).first()
                if correct_answer is not None:
                    correct_answers[question_id] = correct_answer.answer_letter

        # Calculate the score
        total_questions = len(correct_answers)
        correct_count = sum \
            (1 for question_id, user_answer in user_answers.items() if user_answer == correct_answers.get(question_id))

        if total_questions > 0:
            score_percentage = (correct_count / total_questions) * 100
        else:
            score_percentage = 0

        # Check if the user has already taken the same quiz
        quiz_id = int(request.form.get('quiz_id'))
        user_id = current_user.id
        existing_score = Scores.query.filter_by(user_id=user_id, quiz_id=quiz_id).first()

        if existing_score:
            # Update the existing score
            existing_score.score_percentage = score_percentage
            existing_score.datetime = dt.now()
        else:
            # Create a new Scores record
            score = Scores(user_id=user_id, datetime=dt.now(), score_percentage=score_percentage, quiz_id=quiz_id)
            db.session.add(score)

        db.session.commit()

        # Return the score as JSON response
        return jsonify(score_percentage=score_percentage)

    except Exception as e:
        # Log the error with traceback
        import traceback
        traceback.print_exc()

        # Return an error response
        return jsonify({'error': 'Error processing quiz submission'}), 400


@main.route('/quiz/<int:quiz_id>/score', methods=['GET'])
@login_required
def scoreboard(quiz_id):
    users = Scores.query.order_by(Scores.score_percentage.desc()).filter_by(quiz_id=quiz_id).all()
    quiz = Quiz.query.filter_by(id=quiz_id).first()
    return render_template('main/scoreboard.html', users=users, quiz=quiz)


@main.route('/quiz', methods=['GET', 'POST'])
@login_required
def quiz_view():
    if request.method == 'POST':
        prompt = request.form['prompt']
        res = generateChatResponse(prompt)

        # Store the quiz data in the session

        # print("Generated Quiz Data:", res)
        if 'error' in res:
            session.pop('quiz_data', None)
            return jsonify(res), 400
        session['quiz_data'] = res
        return jsonify(res), 200

    return render_template('main/quiz.html')


@main.route('/generate-quiz', methods=['POST'])
@login_required
def generate_quiz():
    user_id = current_user.id

    current_datetime = dt.now()

    # Retrieve the quiz data from the request
    res = session.get('quiz_data', None)

    print("Generated Quiz Data:", res)

    if res is None:
        return jsonify({"error": "Quiz data not found in request"}), 400

    # Determine the quiz_number for the user
    quiz_number = (
        db.session.query(func.max(Quiz.quiz_number))
        .filter_by(user_id=user_id)
        .scalar()
    )
    if quiz_number is None:
        quiz_number = 1
    else:
        quiz_number += 1

    # Create a new Quiz object
    quiz = Quiz(user_id=user_id, datetime=current_datetime, quiz_number=quiz_number)
    db.session.add(quiz)
    db.session.commit()

    question_text = res['question_text']
    correct_answer = res['correct_answer']
    answer_options = res['answer_options']

    for i in range(len(question_text)):
        question = GameQuestions(
            user_id=user_id,
            datetime=current_datetime,
            quiz_number=quiz_number,
            question_number=i + 1,
            question_text=question_text[i],
            quiz_id=quiz.id
        )
        db.session.add(question)
        db.session.commit()

        answer_options_per_question = answer_options[i * 4: (i + 1) * 4]

        for j, (option_letter, option_text) in enumerate(answer_options_per_question, start=1):
            correct_answer_option = ord(correct_answer[i].lower()) - ord('a') + 1
            correct_answer_flag = (j == correct_answer_option)

            answer = GameAnswers(
                user_id=user_id,
                datetime=current_datetime,
                quiz_id=quiz.id,
                question_id=question.id,
                answer_letter=option_letter,
                answer_text=option_text,
                correct_answer=correct_answer_flag
            )
            db.session.add(answer)
            db.session.commit()
    session.pop('quiz_data', None)
    return jsonify({"success": "Generate Quiz Successfully"}), 200


@main.route('/delete-quiz/<int:quiz_id>', methods=['GET', 'POST'])
@login_required
def delete_quiz(quiz_id):
    # Retrieve the quiz by ID
    quiz = Quiz.query.get(quiz_id)

    print(quiz)

    if not quiz:
        flash('Quiz not found', 'error')
        return redirect(url_for('main.dashboard'))

    # Check if the logged-in user is the owner of the quiz
    if quiz.user_id != current_user.id:
        flash('You are not authorized to delete this quiz', 'error')
        return redirect(url_for('main.dashboard'))

    # Delete the associated GameQuestions and GameAnswers records
    Scores.query.filter_by(user_id=current_user.id, quiz_id=quiz_id).delete()
    game_questions = GameQuestions.query.filter_by(quiz_id=quiz.id).all()
    for question in game_questions:
        GameAnswers.query.filter_by(question_id=question.id).delete()
    GameQuestions.query.filter_by(quiz_id=quiz.id).delete()

    db.session.delete(quiz)
    db.session.commit()

    flash('Quiz deleted successfully', 'success')
    return redirect(url_for('main.dashboard'))


@main.route('/rename_quiz/<int:quiz_id>', methods=['POST'])
@login_required
def rename_quiz(quiz_id):
    new_name = request.form.get('new_name')
    print("New Name:", new_name)
    # Update the quiz_name in the database
    quiz = Quiz.query.get(quiz_id)
    quiz.quiz_name = new_name
    db.session.commit()

    return redirect(url_for('main.dashboard'))


@main.route('/toggle_public', methods=['POST'])
def toggle_public():
    data = request.get_json()
    quiz_id = data.get('quizId')
    is_public = data.get('isPublic')

    # Update the public_quiz attribute for the quiz with the given ID
    quiz = Quiz.query.get(quiz_id)
    if quiz:
        quiz.public_quiz = is_public
        db.session.commit()

    return jsonify({'success': True})

app/templates/main/dashboard.html
{% extends 'base.html' %} 

{% block content %}
<h1>Welcome to the Dashboard</h1>
<a class="btn btn-primary" href="{{ url_for('main.quiz_view') }}"
  >Create a new Quiz</a
><br /><br />
<h2>My quizzes</h2>
<div class="row mt-4">
  {% for quiz in user_quizzes %}
  <div class="col-md-4">
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">
          {% if quiz.quiz_name %} {{ quiz.quiz_name }} {% else %} Quiz {{
          quiz.quiz_number }} {% endif %}
        </h5>
        <p class="card-text">Created at: {{ quiz.datetime|safe }}</p>
        <div class="d-flex justify-content-between">
          <a
            class="btn btn-primary"
            href="{{ url_for('main.quiz_page', user_id=quiz.user_id, quiz_id=quiz.id) }}"
            >Play</a
          >
          <button class="btn btn-info">Share</button>
        </div>
        <div class="form-check form-switch mt-3">
          <input
            class="form-check-input"
            type="checkbox"
            id="privacy-toggle-{{ quiz.id }}"
            {%
            if
            quiz.public_quiz
            %}checked{%
            endif
            %}
            data-csrf="{{ csrf_token() }}"
            onchange="togglePublic({{ quiz.id }})"
          />
          <label
            class="form-check-label"
            for="privacy-toggle-{{ quiz.quiz_number }}"
            >Public</label
          >
        </div>
        <input type="hidden" id="csrf-token" value="{{ csrf_token() }}" />

        <div class="btn-group mt-2">
          <button
            class="btn btn-secondary"
            data-toggle="modal"
            data-target="#renameModal{{ quiz.id }}"
            onclick="showRenameModal({{ quiz.id }})"
          >
            Rename
          </button>
          <a
            class="btn btn-dark"
            href="{{ url_for('main.delete_quiz', quiz_id=quiz.id) }}"
            onclick="return confirm('Are you sure you want to delete this quiz?')"
            >Delete</a
          >
        </div>
      </div>
    </div>
  </div>

  <!-- Rename Modal -->
  <div
    class="d-none rename-modal-overlay"
    id="renameModal{{ quiz.id }}"
    tabindex="-1"
    role="dialog"
    aria-labelledby="renameModal{{ quiz.id }}Label"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="renameModal{{ quiz.id }}Label">
            Rename Quiz
          </h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form
            action="{{ url_for('main.rename_quiz', quiz_id=quiz.id) }}"
            method="POST"
          >
            <!-- Include the CSRF token -->
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

            <div class="form-group">
              <label for="newName">New Name:</label>
              <input
                type="text"
                class="form-control"
                id="newName{{ quiz.id }}"
                name="new_name"
                required
              />
            </div>
            <button
              type="submit"
              class="btn btn-primary"
              id="saveButton{{ quiz.id }}"
            >
              Save
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>

  {% endfor %}
  <div class="col-12"><h2>Public quizzes</h2></div>
  {% for quiz in public_quizzes %}
  <div class="col-md-4">
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">
          {% if quiz.quiz_name %} {{ quiz.quiz_name }} {% else %} Quiz {{
          quiz.quiz_number }} {% endif %}
        </h5>
        <p class="card-text">Created at: {{ quiz.datetime|safe }}</p>
        <div class="d-flex justify-content-between">
          <a
            class="btn btn-primary"
            href="{{ url_for('main.quiz_page', user_id=quiz.user_id, quiz_id=quiz.id) }}"
            >Play</a
          >
          <button class="btn btn-info">Share</button>
        </div>
      </div>
    </div>
  </div>

  {% endfor %}
</div>
<script>
  function togglePublic(quizId) {
    var checkbox = document.getElementById("privacy-toggle-" + quizId);
    var isPublic = checkbox.checked;
    var csrfToken = checkbox.getAttribute("data-csrf");
    var url = "{{ url_for('main.toggle_public') }}";

    fetch(url, {
      method: "POST",
      body: JSON.stringify({ quizId: quizId, isPublic: isPublic }),
      headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": csrfToken,
      },
    })
      .then((response) => response.json())
      .then((data) => {
        // Handle response as needed
        console.log(data);
      })
      .catch((error) => {
        console.error("Error:", error);
      });
  }

  function showRenameModal(quizId) {
    var modal = document.getElementById("renameModal" + quizId);

    // Remove the d-none class to make the modal visible
    modal.classList.remove("d-none");

    // Add an event listener to the close button to handle the close action
    var closeButton = modal.querySelector(".close");
    closeButton.addEventListener("click", function () {
      // Hide the modal by adding back the d-none class
      modal.classList.add("d-none");
    });
  }
</script>
{% endblock %}

app/templates/main/generated-quiz.html
{% extends 'base.html' %}

{% block nav_title %}
{% if quiz.quiz_name %} 
Quiz - {{ quiz.quiz_name }} 
{% else %} 
Quiz 
{{ quiz.quiz_number }} 
{% endif %}
{% endblock nav_title %}


{% block content %}
<div
  class="container d-flex flex-column justify-content-center align-items-center"
>
  <form id="quiz-form" action="{{ url_for('main.submit_quiz') }}" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <input type="hidden" name="quiz_id" value="{{ quiz.id }}" />

    {% for question in questions %}
    <h3>Question {{ question.question_number }}</h3>
    <p>{{ question.question_text }}</p>
    {% set current_question_id = question.id %} 
    {% for answer in answer_options%} 
    {% if answer.question_id == current_question_id %}
    <label class="radio-label">
      <input
        type="radio"
        name="answer_{{ question.id }}"
        value="{{ answer.answer_letter }}"
      />
      {{ answer.answer_letter }}. {{ answer.answer_text }}
    </label>
    <br />
    {% endif %} 
    {% endfor %} 
    {% endfor %}

    <button id="submit-button" class="btn btn-primary" type="submit">
      Submit
    </button>
  </form>

  <div id="score-div" class="d-none">
    <h2 id="score-text"></h2>
    <a class="btn btn-primary" href="{{ url_for("main.scoreboard", quiz_id=quiz.id) }}">
      Scoreboard
    </a>       
  </div>
</div>
{% endblock %} 

{% block footer %}
<script>
  $(document).ready(function () {
    $("#quiz-form").submit(function (event) {
      event.preventDefault();

      var form = $(this);
      var url = form.attr("action");

      $.ajax({
        type: "POST",
        url: url,
        data: form.serialize(),
        success: function (response) {
          console.log(response)
          var scorePercentage = response.score_percentage;
          $("#score-text").text("Your score is " + scorePercentage + "%");
          $("#score-div").removeClass("d-none");
        },
        error: function (error) {
          console.log("Failed to submit the quiz.");
        },
      });
    });
  });
</script>
{% endblock %}

app/templates/main/quiz.html
{% extends 'base.html' %}

{% block content %}
<div class="container d-flex flex-column justify-content-center align-items-center">
  <h1 class="mt-5">Generate a quiz</h1>
  <p class="text-center">
    Enter the keywords or describing sentence about the quiz below. For example
    "Music of the 80s, 2 questions". If the Number of questions is not
    specified, 10 questions will be generated.
  </p>
  <div  class="d-flex justify-content-center align-items-center">
    <img id="spinner" src="{{ url_for('static', filename='Spinner.gif') }}" alt="spinner.gif"  class="d-none">
  </div>
  <div  class="d-flex justify-content-center align-items-center">
    <p id="error-mg" class="text-danger d-none"></p>
  </div>
  <div id="list-group" class="list-group w-auto d-none"></div>
</br>
  <div id="quiz-button" class="input-group justify-content-center mb-3 d-none">
    <button id="generate-quiz-button" class="btn btn-primary">
      Generate Quiz
    </button>
    <div class="input-group justify-content-center mb-3">
      <p class="text-center">
        </br>Or <a href="{{ url_for('main.quiz_view') }}">Refresh</a> the page a new prompt below to generate a new quiz!
      </p>
    </div>
  </div>

  <div class="input-group mb-3">
    <input type="text" class="form-control" id="chat-input" />
    <div class="input-group-append">
      <button id="gpt-button" class="btn btn-primary">Enter</button>
    </div>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" /> <!-- CSRF token -->
  </div>
  <p class="text-center">
    When entering a prompt be patient. It can take up to a minute for the quiz
    to be generated.
  </p>
</div>
{% endblock %}

{% block footer %}
<script>
  function alertMsg(textStr){
    // Update the text content with a message
    $("#error-mg").text(textStr);
    $("#error-mg").removeClass("d-none");

    // Remove the message after 
    setTimeout(function() {
      $("#error-mg").text("");
      $("#error-mg").addClass("d-none");
    }, 1500);
  }
</script>

<script src="{{ url_for('static', filename='js/quiz.js') }}"></script>
<script>
  $(document).ready(function() {
    $('#generate-quiz-button').click(function(event) {

      $("#gpt-button").prop("disabled", true);
      $("#generate-quiz-button").prop("disabled", true);
      $("#list-group").addClass("d-none");
      $("#spinner").removeClass("d-none");
  
      event.preventDefault();
      var prompt = $('#chat-input').val();
      var csrfToken = $('input[name="csrf_token"]').val(); // Retrieve the CSRF token
  
      $.ajax({
        url: '{{ url_for("main.generate_quiz") }}',
        type: 'POST',
        headers: {
          'X-CSRFToken': csrfToken // Set the CSRF token as a header
        },
        data: { prompt: prompt },
        success: function(response) {
          // Handle the response
          window.location.href = "/dashboard";
        },
        error: function(error) {
          // Handle the error
          console.log(error)
        }
      });
    });
  });
</script>
{% endblock %}

app/templates/main/scoreboard.html
{% extends 'base.html' %} 


{% block content %}
<div class="container">
  <h1>Quiz Scores</h1>
  <h2>{{ quiz.quiz_number }}</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Users</th>
        <th>Timestamp</th>
        <th>Score Percentage</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
      <tr>
        <td>{{ user.user.username }}</td>
        <td>{{ user.datetime.strftime('%b, %d %Y %I:%M %p') }}</td>
        <td>{{ user.score_percentage }} %</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}