app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash, jsonify
from werkzeug.security import check_password_hash, generate_password_hash
from datetime import datetime as dt
from sqlalchemy import func
from datetime import datetime
import re


from .aiapi import generateChatResponse
from .extensions import db
from .models import User, GameQuestions, GameAnswers, Quiz, Scores

main = Blueprint('main', __name__)



@main.route('/user-<int:user_id>-quiz-<int:quiz_number>', methods=['GET'])
def quiz_page(user_id, quiz_number):
    try:
        quiz = Quiz.query.filter_by(user_id=user_id, quiz_number=quiz_number).first()
        if quiz is None:
            return "Quiz not found", 404

        if quiz.public_quiz or ('user_id' in session and session['user_id'] == user_id):
            questions = GameQuestions.query.filter_by(quiz_id=quiz.id).all()
            if not questions:
                return "No questions found for the quiz", 404

            answer_options = []
            for question in questions:
                options = GameAnswers.query.filter_by(question_id=question.id).all()
                answer_options.extend(options)

            user_scores = Scores.query.filter_by(user_id=session.get('user_id'), quiz_id=quiz.id).all()
            existing_scores_count = len(user_scores)

            return render_template('generated-quiz.html', quiz=quiz, questions=questions, answer_options=answer_options, existing_scores_count=existing_scores_count)

        return "Unauthorized", 401

    except Exception as e:
        # Log the error with traceback
        import traceback
        traceback.print_exc()
        flash('Error loading the quiz.', 'error')
        return redirect(url_for('main.dashboard'))


@main.route('/quiz', methods=['GET', 'POST'])
def quiz_view():
    if request.method == 'POST':
        if 'user_id' in session:
            user_id = session['user_id']
        else:
            return "User not logged in", 401

        prompt = request.form['prompt']
        res = generateChatResponse(prompt)

        # Store the quiz data in the session
        session['quiz_data'] = res
        #print("Generated Quiz Data:", res) 
        return jsonify(res), 200

    # Clear the quiz data from the session
    session.pop('quiz_data', None)

    return render_template('quiz.html')


@main.route('/generate-quiz', methods=['POST'])
def generate_quiz():
    if 'user_id' in session:
        user_id = session['user_id']
    else:
        return "User not logged in", 401

    current_datetime = dt.now()

    # Retrieve the quiz data from the request
    res = session.get('quiz_data')

    if res is None:
        return "Quiz data not found in request", 400

    # Determine the quiz_number for the user
    quiz_number = (
        db.session.query(func.max(Quiz.quiz_number))
        .filter_by(user_id=user_id)
        .scalar()
    )
    if quiz_number is None:
        quiz_number = 1
    else:
        quiz_number += 1

    # Create a new Quiz object
    quiz = Quiz(user_id=user_id, datetime=current_datetime, quiz_number=quiz_number)
    db.session.add(quiz)
    db.session.commit()

    question_text = res['question_text']
    correct_answer = res['correct_answer']
    answer_options = res['answer_options']

    for i in range(len(question_text)):
        question = GameQuestions(
            user_id=user_id,
            datetime=current_datetime,
            quiz_number=quiz_number,
            question_number=i + 1,
            question_text=question_text[i],
            quiz_id=quiz.id
        )
        db.session.add(question)
        db.session.commit()

        answer_options_per_question = answer_options[i * 4: (i + 1) * 4]

        for j, (option_letter, option_text) in enumerate(answer_options_per_question, start=1):
            correct_answer_option = ord(correct_answer[i].lower()) - ord('a') + 1
            correct_answer_flag = (j == correct_answer_option)

            answer = GameAnswers(
                user_id=user_id,
                datetime=current_datetime,
                quiz_id=quiz.id,
                question_id=question.id,
                answer_letter=option_letter,
                answer_text=option_text,
                correct_answer=correct_answer_flag
            )
            db.session.add(answer)
            db.session.commit()

    return redirect(url_for('main.dashboard')) 


@main.route('/delete-quiz/<int:quiz_id>', methods=['GET', 'POST'])
def delete_quiz(quiz_id):
    if 'user_id' not in session:
        flash('You must be logged in to delete a quiz', 'warning')
        return redirect(url_for('main.login'))

    # Retrieve the quiz by ID
    quiz = Quiz.query.get(quiz_id)

    if not quiz:
        flash('Quiz not found', 'danger')
        return redirect(url_for('main.dashboard'))

    # Check if the logged-in user is the owner of the quiz
    if quiz.user_id != session['user_id']:
        flash('You are not authorized to delete this quiz', 'danger')
        return redirect(url_for('main.dashboard'))

    # Delete the associated GameQuestions and GameAnswers records
    game_questions = GameQuestions.query.filter_by(quiz_id=quiz.id).all()
    for question in game_questions:
        GameAnswers.query.filter_by(question_id=question.id).delete()
    GameQuestions.query.filter_by(quiz_id=quiz.id).delete()

    # Delete the quiz
    db.session.delete(quiz)
    db.session.commit()

    flash('Quiz deleted successfully', 'success')
    return redirect(url_for('main.dashboard'))


@main.route('/rename_quiz/<int:quiz_id>', methods=['POST'])
def rename_quiz(quiz_id):
    new_name = request.form.get('new_name')
    print("New Name:", new_name)
    # Update the quiz_name in the database
    quiz = Quiz.query.get(quiz_id)
    quiz.quiz_name = new_name
    db.session.commit()

    return redirect(url_for('main.dashboard'))


@main.route('/submit-quiz', methods=['POST'])
def submit_quiz():
    try:
        user_answers = {}
        for key, value in request.form.items():
            if key.startswith('answer_'):
                question_id = int(key.split('_')[1])
                user_answers[question_id] = value

        # Fetch correct answers from the database based on the question IDs
        correct_answers = {}
        for question_id in user_answers.keys():
            question = GameQuestions.query.get(question_id)
            if question is not None:
                correct_answer = GameAnswers.query.filter_by(question_id=question.id, correct_answer=True).first()
                if correct_answer is not None:
                    correct_answers[question_id] = correct_answer.answer_letter

        # Calculate the score
        total_questions = len(correct_answers)
        correct_count = sum(1 for question_id, user_answer in user_answers.items() if user_answer == correct_answers.get(question_id))

        if total_questions > 0:
            score_percentage = round((correct_count / total_questions) * 100)
        else:
            score_percentage = 0

        # Check if the user has already taken the same quiz
        quiz_id = int(request.form.get('quiz_id'))
        user_id = session.get('user_id')

        # Check the number of existing scores for the same user and quiz
        existing_scores_count = Scores.query.filter_by(user_id=user_id, quiz_id=quiz_id).count()

        if existing_scores_count < 3:
            # Create a new Scores record
            score = Scores(user_id=user_id, datetime=dt.now(), score_percentage=score_percentage, quiz_id=quiz_id)
            db.session.add(score)
        else:
            # User has already reached the maximum number of attempts
            return "You have reached the maximum number of quiz attempts.", 400

        db.session.commit()

        # Return the score as JSON response
        return jsonify(score_percentage=score_percentage)

    except Exception as e:
        # Log the error with traceback
        import traceback
        traceback.print_exc()

        # Return an error response
        return "Error processing quiz submission", 400



@main.route('/user-<int:creator_id>-quiz-<int:quiz_number>/score', methods=['GET'])
def scoreboard(creator_id, quiz_number):
    quiz = Quiz.query.filter_by(user_id=creator_id, quiz_number=quiz_number).first()
    scores = Scores.query.filter_by(quiz_id=quiz.id).all()

    # Find the highest score for each user
    user_scores = {}
    for score in scores:
        if score.user.username in user_scores:
            if score.score_percentage > user_scores[score.user.username]:
                user_scores[score.user.username] = score.score_percentage
        else:
            user_scores[score.user.username] = score.score_percentage

    # Convert user_scores dictionary to a list of tuples for rendering in the template
    user_scores_list = [(username, round(score)) for username, score in user_scores.items()]

    return render_template('scoreboard.html', user_scores=user_scores_list, quiz=quiz)


@main.route('/')
def index():
    return render_template('landing.html')

@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        identifier = request.form['identifier'].lower()  # Convert identifier to lowercase
        password = request.form['password']
        user = User.query.filter(db.or_(func.lower(User.email) == identifier, func.lower(User.username) == identifier)).first()  # Use func.lower to convert email and username to lowercase

        if user and check_password_hash(user.password_hash, password):
            session['user_id'] = user.id
            flash('You have been logged in!', 'success')
            return redirect(url_for('main.dashboard'))
        else:
            flash('Username or password is incorrect', 'danger')
    
    session.pop('user_id', None)
    return render_template('login.html')


@main.route('/register', methods=['GET', 'POST'])
def register():

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Quiz Genius!{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap"
    />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{{ url_for('static', filename='images/favicon/favicon.png') }}"
    />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

    {{ toastr.include_jquery() }} {{ toastr.include_toastr_css() }} {{
    toastr.message() }}
  </head>
  <body>
    <nav class="navbar navbar-light">
      <span class="navbar-brand">
        {% block nav_title %} {{ request.path.split('/')[-1].title() }} {%
        endblock nav_title %}
      </span>
      {% if current_user.is_authenticated %}
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if request.path != url_for('main.dashboard') %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.dashboard') }}"
              >Dashboard</a
            >
          </li>
          {% endif %} {% if request.path != url_for('main.quiz_view') %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.quiz_view') }}"
              >Create Quiz</a
            >
          </li>
          {% endif %} {% if request.path != url_for('auth.account') %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.account') }}">Account</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Log out</a>
          </li>
        </ul>
      </div>
      <button
        class="navbar-toggler ml-auto border-0"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      {% else %}
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item"></li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.register') }}"
              >Register</a
            >
          </li>
        </ul>
      </div>
      <button
        class="navbar-toggler ml-auto border-0"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      {% endif %}
    </nav>

    <main class="container mt-3">{% block content %} {% endblock %}</main>

    {{ toastr.include_toastr_js() }} {% block footer %}
    <footer class="container-fluid mt-3">
      <div class="row">
        <div class="col text-center"></div>
      </div>
    </footer>
    {% endblock %}
  </body>
</html>

app/templates/dashboard.html
{% extends 'base.html' %} {% block content %}
<br />
<h1>We welcome <b>{{ user.username|capitalize }}</b> to <b>Quiz Genius!</b></h1>
<br />
<a class="btn btn-primary" href="{{ url_for('main.quiz_view') }}"
  >Create a new Quiz</a
><br /><br />

<h3>My quizzes</h3>
<div class="row mt-4">
  {% for quiz in user_quizzes %}
  <div class="col-md-4">
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">
          {% if quiz.quiz_name %} {{ quiz.quiz_name }} {% else %} Quiz {{
          quiz.quiz_number }} {% endif %}
        </h5>
        <p class="card-text">Created at: {{ quiz.datetime|safe }}</p>
        <div class="d-flex">
          <button
            class="btn btn-info"
            onclick="window.location.href='{{ url_for('main.quiz_page', user_id=quiz.user_id, quiz_number=quiz.quiz_number) }}'"
          >
            Play me
          </button>
          <button
            class="btn btn-info ml-2"
            onclick="window.location.href='{{ url_for('main.scoreboard', creator_id=quiz.user_id, quiz_number=quiz.quiz_number) }}'"
          >
            Scores
          </button>
        </div>
        <div class="form-check form-switch mt-3">
          <input
            class="form-check-input"
            type="checkbox"
            id="privacy-toggle-{{ quiz.id }}"
            {%
            if
            quiz.public_quiz
            %}
            checked
            {%
            endif
            %}
            data-csrf="{{ csrf_token() }}"
            onchange="togglePublic({{ quiz.id }})"
          />
          <label
            class="form-check-label"
            for="privacy-toggle-{{ quiz.quiz_number }}"
            >Public</label
          >
        </div>
        <input type="hidden" id="csrf-token" value="{{ csrf_token() }}" />

        <div class="btn-group mt-2">
          <button
            class="btn btn-secondary"
            data-toggle="modal"
            data-target="#renameModal{{ quiz.id }}"
            onclick="showRenameModal({{ quiz.id }})"
          >
            Rename
          </button>
          <a
            class="btn btn-dark"
            href="{{ url_for('main.delete_quiz', quiz_id=quiz.id) }}"
            onclick="return confirm('Are you sure you want to delete this quiz?')"
            >Delete</a
          >
        </div>
      </div>
    </div>
  </div>

  <!-- Rename Modal -->
  <div
    class="d-none rename-modal-overlay"
    id="renameModal{{ quiz.id }}"
    tabindex="-1"
    role="dialog"
    aria-labelledby="renameModal{{ quiz.id }}Label"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="renameModal{{ quiz.id }}Label">
            Rename Quiz
          </h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form
            action="{{ url_for('main.rename_quiz', quiz_id=quiz.id) }}"
            method="POST"
          >
            <!-- Include the CSRF token -->
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

            <div class="form-group">
              <label for="newName">New Name:</label>
              <input
                type="text"
                class="form-control"
                id="newName{{ quiz.id }}"
                name="new_name"
                required
              />
            </div>
            <button
              type="submit"
              class="btn btn-primary"
              id="saveButton{{ quiz.id }}"
            >
              Save
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>

  {% endfor %}
  <br />
  <div class="col-12">
    <br />
    <h3>Other users' quizzes</h3>
    <br />
  </div>
  {% for quiz in public_quizzes %}
  <div class="col-md-4">
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">
          {% if quiz.quiz_name %} {{ quiz.quiz_name }} {% else %} Quiz {{
          quiz.quiz_number }} {% endif %}
        </h5>
        <p class="card-text">Created at: {{ quiz.datetime|safe }}</p>
        <div class="d-flex">
          <a
            class="btn btn-info"
            href="{{ url_for('main.quiz_page', user_id=quiz.user_id, quiz_number=quiz.quiz_number) }}"
            >Play</a
          >
          <button
            class="btn btn-info ml-2"
            onclick="window.location.href='{{ url_for('main.scoreboard', creator_id=quiz.user_id, quiz_number=quiz.quiz_number) }}'"
          >
            Scores
          </button>
        </div>
      </div>
    </div>
  </div>

  {% endfor %}
</div>
<script>
  function togglePublic(quizId) {
    var checkbox = document.getElementById("privacy-toggle-" + quizId);
    var isPublic = checkbox.checked;
    var csrfToken = checkbox.getAttribute("data-csrf");
    var url = "{{ url_for('main.toggle_public') }}";

    fetch(url, {
      method: "POST",
      body: JSON.stringify({ quizId: quizId, isPublic: isPublic }),
      headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": csrfToken,
      },
    })
      .then((response) => response.json())
      .then((data) => {
        // Handle response as needed
        console.log(data);
      })
      .catch((error) => {
        console.error("Error:", error);
      });
  }

  function showRenameModal(quizId) {
    var modal = document.getElementById("renameModal" + quizId);

    // Remove the d-none class to make the modal visible
    modal.classList.remove("d-none");

    // Add an event listener to the close button to handle the close action
    var closeButton = modal.querySelector(".close");
    closeButton.addEventListener("click", function () {
      // Hide the modal by adding back the d-none class
      modal.classList.add("d-none");
    });
  }
</script>
{% endblock %}

app/templates/generated-quiz.html
{% extends 'base.html' %}{% block navbar_brand %}{% if quiz.quiz_name %} {{ quiz.quiz_name }} {% else %} Quiz {{
  quiz.quiz_number }} {% endif %}{% endblock %}
{% block content %}
<div class="container d-flex flex-column justify-content-center align-items-center">
  <form id="quiz-form" action="{{ url_for('main.submit_quiz') }}" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <input type="hidden" name="quiz_id" value="{{ quiz.id }}" />

    {% for question in questions %}
    <h4>Question {{ question.question_number }}</h4>
    <p>{{ question.question_text }}</p>
    {% set current_question_id = question.id %}
    {% for answer in answer_options %}
    {% if answer.question_id == current_question_id %}
    <label class="radio-label">
      <input
        type="radio"
        name="answer_{{ question.id }}"
        value="{{ answer.answer_letter }}"
      />
      {{ answer.answer_letter }}. {{ answer.answer_text }}
    </label>
    <br />
    {% endif %}
    {% endfor %}
    <br />
    {% endfor %}
    <button id="submit-button" class="btn btn-primary" type="submit">
      Submit
    </button>
    <br />
  </form>

  <div id="score-div" class="d-none">
    <h2 id="score-text"></h2>
    {% if existing_scores_count >= 3 %}
    <p>You have attempted this quiz already 3 times. Please try another quiz.</p>
    {% endif %}
    <button class="btn btn-primary" onclick="window.location.href='{{ url_for("main.scoreboard", creator_id=quiz.user_id, quiz_number=quiz.quiz_number) }}'">
      Scoreboard
    </button>
    <br />
  </div>
</div>
{% endblock %}
{% block footer %}
<script>
  $(document).ready(function () {
    $("#quiz-form").submit(function (event) {
      event.preventDefault();

      var form = $(this);
      var url = form.attr("action");

      $.ajax({
        type: "POST",
        url: url,
        data: form.serialize(),
        success: function (response) {
          var scorePercentage = response.score_percentage;
          $("#score-text").text("Your score is " + scorePercentage + "%");
          $("#score-div").removeClass("d-none");
        },
        error: function (error) {
          $("#score-div").removeClass("d-none");
        },
      });
    });
  });
</script>
{% endblock %}

app/templates/landing.html
{% extends 'base.html' %} {% block navbar %} {% endblock %} {% block content %}
<div class="separate-div"></div>
<div class="row">
  <div class="col-6">
    <img
      src="{{ url_for('static', filename='images/logo.svg') }}"
      alt="Quiz IT!"
      class="logo"
    />
    <p class="main-para">
      Generate AI powered quizzes with just minutes to enjoy with friends,
      coworkers and loved ones!
    </p>
    <div class="buttons">
      <a href="{{ url_for('main.login') }}">
        <button class="btn btn-primary">Login ></button>
      </a>
      <a href="{{ url_for('main.register') }}">
        <button class="btn btn-primary" id="reg_btn">
          <span>Register > </span>
        </button>
      </a>
    </div>
  </div>
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %} {% block title %}Log in{% endblock %} {% block navbar
%}
<nav class="navbar navbar-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item"></li>
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.register') }}">Register</a>
      </li>
    </ul>
  </div>
  <button
    class="navbar-toggler ml-auto border-0"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>
{% endblock %} {% block content %}
<div
  class="container d-flex flex-column justify-content-center align-items-center"
>
  <h1 class="text-center page-header">Log in</h1>
  <p class="text-center">Log in to make some magic!</p>
  {% with messages = get_flashed_messages(with_categories=true) %} {% if
  messages %}
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      {% for category, message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %} {% endwith %}
  <form method="POST" action="{{ url_for('main.login') }}" class="col-5">
    <div class="form-group">
      <label for="identifier">Username or Email:</label>
      <input
        type="text"
        name="identifier"
        id="identifier"
        required
        class="form-control w-100 form-control-lg"
      />
    </div>
    <div class="form-group">
      <label for="password">Password:</label>
      <input
        type="password"
        name="password"
        id="password"
        required
        class="form-control w-100 form-control-lg"
      />
    </div>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <!-- CSRF token -->
    <button type="submit" class="btn btn-primary btn-block">Login ></button>
  </form>
  <small
    >Or
    <a href="{{ url_for('main.register') }}">create an account</a>
    instead.</small
  >
</div>
{% endblock %}

app/templates/quiz.html
{% extends 'base.html' %} 
{% block content %}
<div class="container d-flex flex-column justify-content-center align-items-center">
  <h1 class="mt-5"><b>Quiz generator</b></h1>
  <br />
  <p class="text-center">
    Enter the keywords or describing sentence about the quiz below. For example
    <b>"Music of the 80s, 2 questions"</b>. If the Number of questions is not
    specified, 10 questions will be generated.
  </p>
  <div id="quiz-button" class="input-group justify-content-center mb-3 d-none">
    <button id="generate-quiz-button" class="btn btn-primary">
      Generate the quiz now!
    </button>
    <div class="input-group justify-content-center mb-3">
      <p class="text-center">
      </br>After pushing Generate the quiz now! button, <b>please wait</b> until you are redirected to Dashboard! </br></br>If you are not happy with provided quiz, please <a href=".">Refresh</a> the page and try again.
      </p>
    </div>
  </div>
  <div id="list-group" class="list-group w-auto"></div>
</br>


  <div class="input-group mb-3">
    <input type="text" class="form-control" id="chat-input" />
    <div class="input-group-append">
      <button id="gpt-button" class="btn btn-primary">Enter prompt</button>
    </div>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" /> <!-- CSRF token -->
  </div>
  <p class="text-center">
    When entering a prompt be patient. It can take <b>several minutes</b> for the quiz
    to be generated.
  </p>
</div>
{% endblock %} 
{% block footer %}

<script src="{{ url_for('static', filename='js/quiz.js') }}"></script>
<script>
  $(document).ready(function() {
    $('#gpt-button').click(function(event) {
      event.preventDefault();
      var prompt = $('#chat-input').val();
      var csrfToken = $('input[name="csrf_token"]').val(); // Retrieve the CSRF token
  
      $.ajax({
        url: '{{ url_for("main.generate_quiz") }}',
        type: 'POST',
        headers: {
          'X-CSRFToken': csrfToken // Set the CSRF token as a header
        },
        data: { prompt: prompt },
        success: function(response) {
          // Handle the response
          $('#quiz-button').removeClass('d-none'); // Show the quiz button
        },
        error: function(error) {
          // Handle the error
        }
      });
    });
  });
  
</script>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %} {% block title %}Register{% endblock %} {% block
navbar %}

<nav class="navbar navbar-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item"></li>
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.register') }}">Register</a>
      </li>
    </ul>
  </div>
  <button
    class="navbar-toggler ml-auto border-0"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>
{% endblock %} {% block content %}
<div
  class="container d-flex flex-column justify-content-center align-items-center"
>
  <h1 class="text-center page-header">Register</h1>
  <p class="text-center">Just a few clicks until your first quiz!</p>

  {% with messages = get_flashed_messages() %} {% if messages %}
  <div class="alert alert-danger">
    <ul class="mb-0">
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %} {% endwith %}
  <form method="POST" action="{{ url_for('main.register') }}" class="col-5">
    <div class="form-group">
      <label for="username">Username:</label>
      <input
        type="text"
        name="username"
        id="username"
        required
        class="form-control w-100 form-control-lg"
      />
    </div>
    <div class="form-group">
      <label for="email">Email:</label>
      <input
        type="email"
        name="email"
        id="email"
        required
        class="form-control w-100 form-control-lg"
      />
    </div>
    <div class="form-group">
      <label for="password">Password:</label>
      <input
        type="password"
        name="password"
        id="password"
        required
        class="form-control w-100 form-control-lg"
      />
    </div>
    <div class="form-group">
      <label for="confirm_password">Confirm Password:</label>
      <input
        type="password"
        name="confirm_password"
        id="confirm_password"
        required
        class="form-control w-100 form-control-lg"
      />
    </div>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <!-- CSRF token -->
    <small
      >PS! Password should be at least 8 characters, include at least one digit,
      one uppercase letter, one lowercase letter, and one symbol.</small
    >
    <br /><br />
    <button type="submit" class="btn btn-primary btn-block">Register</button>
  </form>
  <small>Or <a href="{{ url_for('main.login') }}">log in</a> instead.</small>
</div>
{% endblock %}